import { Route } from "./types";
import {
	About,
	Avatar,
	Base64,
	Blog,
	Book,
	BorderRadius,
	BoxShadow,
	ColorPicker,
	Course,
	DataGenerator,
	DesignSystem,
	Feedback,
	Github,
	Home,
	Icon,
	ImageGeneratorFromColors,
	JsonToTypescript,
	MarkdownEditor,
	Mimetype,
	Movie,
	News,
	PageNotFound,
	Pixel,
	Platform,
	Plugin,
	QRcode,
	ShadesAndTints,
	Sorting,
	SvgFormatter,
	TableGenerator,
	TableOfContent,
	TextEditor,
	Tool,
	TvSeries,
	UiUx,
	YouTube,
} from "pages/pages";

const routes: Route[] = [
	{
		path: "/newsfeed",
		title: "Newsfeed",
		description: "Get the scoop! Fresh news served daily.",
		component: News,
	},
	{
		path: "/colors/cp",
		title: "Color Picker",
		description: "Unleash your inner Picasso & pick the perfect hue.",
		component: ColorPicker,
	},
	{
		path: "/colors/shades-tints",
		title: "Shades & Tints",
		description: "50 shades of any color you fancy!",
		component: ShadesAndTints,
	},
	{
		path: "/css/br",
		title: "Border Radius",
		description: "Shape up your CSS with some smooth curves.",
		component: BorderRadius,
	},
	{
		path: "/css/bs",
		title: "Box Shadow",
		description: "Add drama to your box! Shadows included.",
		component: BoxShadow,
	},
	{
		path: "/css/svg-formatter",
		title: "SVG Formatter",
		description: "Get your SVGs in shipshape.",
		component: SvgFormatter,
	},
	{
		path: "/converter/base-64",
		title: "Base64",
		description: "Encode, decode, and party in Base64 style.",
		component: Base64,
	},
	{
		path: "/converter/pixel",
		title: "Pixel Converter",
		description: "Pixels to units - like magic, but real!",
		component: Pixel,
	},
	{
		path: "/converter/jtt",
		title: "Json To Typescript",
		description: "Turn your JSON into TypeScript's next top model.",
		component: JsonToTypescript,
	},
	{
		path: "/generator/data",
		title: "Data",
		description: "Make it rain with random data.",
		component: DataGenerator,
	},
	{
		path: "/generator/avatar",
		title: "Avatar",
		description: "Create funky avatars. No airbending skills required.",
		component: Avatar,
	},
	{
		path: "/generator/igfc",
		title: "Image",
		description: "Craft beautiful images from a simple palette of colors.",
		component: ImageGeneratorFromColors,
	},
	{
		path: "/generator/qrcode",
		title: "QR Code",
		description: "Generate QR codes - like barcodes, but squarer!",
		component: QRcode,
	},
	{
		path: "/generator/sorting",
		title: "Sorting",
		description: "Sort arrays like a boss.",
		component: Sorting,
	},
	{
		path: "/resource/blog",
		title: "Blog",
		description: "Feast your eyes on our riveting reads.",
		component: Blog,
	},
	{
		path: "/resource/book",
		title: "Book",
		description: "Dive into our library of literary treasures.",
		component: Book,
	},
	{
		path: "/resource/course",
		title: "Course",
		description: "Learn new tricks without any Hogwarts tuition fees.",
		component: Course,
	},
	{
		path: "/resource/design-system",
		title: "Design System",
		description: "Marvel at the methods behind our design madness.",
		component: DesignSystem,
	},
	{
		path: "/resource/github",
		title: "Github",
		description: "Peek at our code in its natural habitat.",
		component: Github,
	},
	{
		path: "/resource/icon",
		title: "Icon",
		description: "Icons galore! Pick 'em, use 'em, love 'em.",
		component: Icon,
	},
	{
		path: "/resource/movie",
		title: "Movie",
		description: "Roll out the red carpet for our movie collection.",
		component: Movie,
	},
	{
		path: "/resource/platform",
		title: "Platform",
		description: "Step up to our platform of choice resources.",
		component: Platform,
	},
	{
		path: "/resource/plugin",
		title: "Plugin",
		description: "Plugins to power up your projects.",
		component: Plugin,
	},
	{
		path: "/resource/tool",
		title: "Tool",
		description: "Tools of the trade to make your work a breeze.",
		component: Tool,
	},
	{
		path: "/resource/tv-series",
		title: "TV Series",
		description: "Get comfy with our collection of binge-worthy TV series.",
		component: TvSeries,
	},
	{
		path: "/resource/ui-ux",
		title: "UI/UX",
		description: "Feast your eyes on the finest UI/UX resources.",
		component: UiUx,
	},
	{
		path: "/resource/youtube",
		title: "Youtube",
		description: "Dive into our YouTube video vault.",
		component: YouTube,
	},
	{
		path: "/markdown/me",
		title: "Editor",
		description: "Markdown Editor - for words that mark the spot.",
		component: MarkdownEditor,
	},
	{
		path: "/markdown/md-table-generator",
		title: "Table",
		description: "Create tables that would make any spreadsheet jealous.",
		component: TableGenerator,
	},
	{
		path: "/markdown/toc",
		title: "Table Of Content",
		description:
			"Organize your thoughts with a click, courtesy of our TOC.",
		component: TableOfContent,
	},
	{
		path: "/text/te",
		title: "Text Editor",
		description: "For those who love to play with words.",
		component: TextEditor,
	},
	{
		path: "/information/mimetype",
		title: "Mimetype",
		description: "Find out what type your file fancies itself as.",
		component: Mimetype,
	},
	{
		path: "/",
		title: "",
		description: "Welcome home!",
		component: Home,
	},
	{
		path: "/about",
		title: "About",
		description: "All the juicy details about us.",
		component: About,
	},
	{
		path: "/feedback",
		title: "Feedback",
		description: "We're all ears for your cheers or jeers.",
		component: Feedback,
	},
	{
		path: "*",
		title: "Page Not Found",
		description: "Oops! We've seemed to misplace this page.",
		component: PageNotFound,
	},
];

export { routes };
